main:
  - identifier: about
    name: About
    url: /about
    weight: 100
  - identifier: browse
    name: browse
    url: /browse
    weight: 200
  - identifier: random
    name: Random
    url: /random
    weight: 300
