main:
  - identifier: about
    name: About
    url: /about
    weight: 100
  - identifier: contact
    name: Contact
    url: /contact
    weight: 200
  - identifier: random
    name: Random
    url: /random
    weight: 300
